---
- name: mha user check
  user: name=mha group=mysql state=present
  register: mha_run_user

- name: copy mha node file to host
  copy: src="{{ mha_node_rpm_path }}" dest=/root owner=root group=root mode=0444

- name: install mha node
  yum: name="/root/{{ mha_node_rpm }}" state=present

- name: ensure .ssh dir exists
  file:
    dest: "/home/mha/.ssh"
    owner: mha 
    group: mysql
    mode: 0700
    state: directory
- name: copy mha ssh file
  copy:
    src: "/home/mha/.ssh/{{ item }}"
    dest: "/home/mha/.ssh/{{ item }}"
    owner: mha 
    group: mysql
    mode: "{% if item == 'id_rsa' %} 0600 {% else %} 0644 {% endif %}"
  with_items:
    - id_rsa
    - id_rsa.pub
    - authorized_keys
    - known_hosts
