---
- name: Ensure replication user exists on host.
  mysql_user:
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    name: "{{ mysql_replication_user_name }}"
    host: "{{ mysql_replication_user_host | default('127.0.0.1') }}"
    password: "{{ mysql_replication_user_password }}"
    priv: "{{ mysql_replication_user_priv | default('*.*:REPLICATION SLAVE') }}"
    state: present
  when: >
    mysql_replication_role
    and mysql_replication_user_name
    and ( mysql_replication_master != '' )

- name: Check slave replication status.
  mysql_replication: 
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    mode: getslave
  ignore_errors: true
  register: slave
  when: >
    mysql_replication_role == 'slave'
    and (mysql_replication_master != '')

- name: Check master replication status.
  mysql_replication: 
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    mode: getmaster
  delegate_to: "{{ mysql_replication_master }}"
  ignore_errors: true
  register: master
  when: >
    slave
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')

- name: Configure replication on the slave.
  mysql_replication:
        login_user: "{{ mysql_root_username }}"
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: "{{ mysql_socket }}"
        mode: changemaster
        master_host: "{{ mysql_replication_master }}"
        master_port: "{{ mysql_replication_port }}"
        master_user: "{{ mysql_replication_user_name }}"
        master_password: "{{ mysql_replication_user_password }}"
        master_log_file: "{{ master.File }}"
        master_log_pos: "{{ master.Position }}"
  ignore_errors: True
  when: >
    slave
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')
    and mysql_replication_user_name
    and (gtid_mode != 1 or percona_ver != 56)

- name: Configure replication on the slave with gtid mode.
  mysql_replication:
        login_user: "{{ mysql_root_username }}"
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: "{{ mysql_socket }}"
        mode: changemaster
        master_host: "{{ mysql_replication_master }}"
        master_port: "{{ mysql_replication_port }}"
        master_user: "{{ mysql_replication_user_name }}"
        master_password: "{{ mysql_replication_user_password }}"
        master_auto_position: 1
  ignore_errors: True
  when: >
    slave
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')
    and mysql_replication_user_name
    and (percona_ver == 56 and gtid_mode == 1)

- name: Start replication.
  mysql_replication:
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    mode: startslave
  ignore_errors: True
  when: >
    slave
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')
