---
- name: Disallow root login remotely
  shell: ./use -NBe "{{ item }}" chdir="{{ mysql_nodedir }}"
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Get list of hosts for the root user.
  shell: ./use -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  args:
    chdir: "{{ mysql_nodedir }}"
  register: mysql_root_hosts
  changed_when: false

- name: update MySQL root password for localhost root account
  shell: >
     ./use -uroot -NBe
     'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}");'
  args:
    chdir: "{{ mysql_nodedir }}"
  with_items: mysql_root_hosts.stdout_lines
  when: mysql_root_password_update

- name: Copy my.cnf global MySQL configuration.
  template:
    src: user-my.cnf.j2
    dest: "{{ mysql_nodedir }}/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Get list of hosts for the anonymous user.
  shell: ./use -NBe 'SELECT Host FROM mysql.user WHERE User = ""' chdir="{{ mysql_nodedir }}"
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous MySQL users.
  shell: ./use -uroot -NBe 'DELETE FROM mysql.user WHERE User = "" AND Host="{{ item }}"'
  args:
    chdir: "{{ mysql_nodedir }}" 
  with_items: mysql_anonymous_hosts.stdout_lines

- name: Add monitor user.
  shell: >
     ./use -uroot -NBe
     'GRANT PROCESS, SUPER, REPLICATION SLAVE ON *.* TO {{ monitor_user }}@`{{ monitor_host }}` IDENTIFIED BY PASSWORD "*1975D095AC033CAF4E1BF94F7202A9BBFEEB66F1"'
  args:
    chdir: "{{ mysql_nodedir }}"
